version: '3.8'

services:
  movies-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: movies-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # volumes:
    #   # Optional: Mount database files if you want persistence
    #   - ./db:/app/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: nginx reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: movies-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - movies-api
  #   restart: unless-stopped 